name: Dev Deployment

on:
  push:
    branches: 
      - dev

env:
  GCP_REGISTRY_URL: ${{ secrets.GCP_PROJECT_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_GAR_NAME }}/${{ secrets.GCP_CLOUDRUN_SERVICE }}
  DOCKERFILE_LOCATION: ./Dockerfile
  WORKING_DIRECTORY: .

jobs:
  build-push-deploy:
    name: Build and push artifact to GARk
    runs-on: ubuntu-22.04
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      
      - id: auth
        name: Authenticates to Google Cloud
        uses: google-github-actions/auth@v2
        with: 
          credentials_json: ${{ secrets.GCP_GITHUB_SA_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      
      - name: Set up GCP Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      
      - name: Use Gcloud GCLI
        run: gcloud info

      - name: Docker Auth
        run: |-
          gcloud auth configure-docker ${{ secrets.GCP_PROJECT_REGION }}-docker.pkg.dev --quiet

      - name: Build Docker Image
        run: |
          docker build . --file ${{ env.DOCKERFILE_LOCATION }} --tag ${{ env.GCP_REGISTRY_URL }}:${{ github.sha }}
          docker tag ${{ env.GCP_REGISTRY_URL }}:${{ github.sha }} ${{ env.GCP_REGISTRY_URL }}:latest
        working-directory: ${{ env.WORKING_DIRECTORY }}
      
      - name: Push Image to GAR
        run: |
          docker push ${{ env.GCP_REGISTRY_URL }}:${{ github.sha }}
          docker push ${{ env.GCP_REGISTRY_URL }}:latest

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ secrets.GCP_CLOUDRUN_SERVICE }}
          region: ${{ secrets.GCP_PROJECT_REGION }}
          image: ${{ env.GCP_REGISTRY_URL }}:latest

      - name: Show Cloud Run output
        run: echo ${{ steps.deploy.outputs.url }}

      # - name: Deploy latest image to Cloud Run via CLI
      #   run: |
      #     echo SERVICE_NAME ${{ secrets.GCP_CLOUDRUN_SERVICE }}
      #     gcloud run deploy ${{ secrets.GCP_CLOUDRUN_SERVICE }} \
      #       --image ${{ env.GCP_REGISTRY_URL }}:latest \
      #       --platform managed \
      #       --region ${{ secrets.GCP_PROJECT_REGION }}
      #       --allow-unauthenticated